import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouterManager from "@/components/layout/RouterManager";
import { ToastProvider } from "@/context/ToastContext";
import { AuthProvider } from "@/context/AuthContext";
import { OnboardingProvider } from "@/context/OnboardingContext";
import ProtectedRoute from "@/components/layout/ProtectedRoute";
import { UserProvider } from "@/context/UserContext";
import { ConsultantProvider } from "@/context/ConsultantContext";
import { TeamSelectionProvider } from "@/context/TeamSelectionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href="//fonts.googleapis.com" />
        <link rel="dns-prefetch" href="//fonts.gstatic.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ToastProvider>
            <UserProvider>
              <OnboardingProvider>
                <ConsultantProvider>
                  <TeamSelectionProvider>
                    <RouterManager>
                      <ProtectedRoute>
                        {children}
                      </ProtectedRoute>
                    </RouterManager>
                  </TeamSelectionProvider>
                </ConsultantProvider>
              </OnboardingProvider>
            </UserProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
